#!/bin/bash
python calibration_runs.py free-zinc-calib 0 &
python calibration_runs.py free-zinc-calib 1 &
python calibration_runs.py free-zinc-calib 2 &
python calibration_runs.py free-zinc-calib 3 &
python calibration_runs.py free-zinc-calib 4 &
python calibration_runs.py free-zinc-calib 5 &
python calibration_runs.py free-zinc-calib 6 &
python calibration_runs.py free-zinc-calib 7 &
python calibration_runs.py free-zinc-calib 8 &
python calibration_runs.py free-zinc-calib 9 &
python calibration_runs.py free-zinc-calib 10 &
python calibration_runs.py free-zinc-calib 11 &
python calibration_runs.py free-zinc-calib 12 &
python calibration_runs.py free-zinc-calib 13 &
python calibration_runs.py free-zinc-calib 14 &
python calibration_runs.py free-zinc-calib 15 &
python calibration_runs.py free-zinc-calib 16 &
python calibration_runs.py free-zinc-calib 17 &
python calibration_runs.py free-zinc-calib 18 &
python calibration_runs.py free-zinc-calib 19 &
python calibration_runs.py free-zinc-calib 20 &
python calibration_runs.py free-zinc-calib 21 &
python calibration_runs.py free-zinc-calib 22 &
python calibration_runs.py free-zinc-calib 23
python calibration_runs.py free-zinc-calib 24 &
python calibration_runs.py free-zinc-calib 25 &
python calibration_runs.py free-zinc-calib 26 &
python calibration_runs.py free-zinc-calib 27 &
python calibration_runs.py free-zinc-calib 28 &
python calibration_runs.py free-zinc-calib 29 &
python calibration_runs.py free-zinc-calib 30 &
python calibration_runs.py free-zinc-calib 31 &
python calibration_runs.py free-zinc-calib 32 &
python calibration_runs.py free-zinc-calib 33 &
python calibration_runs.py free-zinc-calib 34 &
python calibration_runs.py free-zinc-calib 35 &
python calibration_runs.py free-zinc-calib 36 &
python calibration_runs.py free-zinc-calib 37 &
python calibration_runs.py free-zinc-calib 38 &
python calibration_runs.py free-zinc-calib 39 &
python calibration_runs.py free-zinc-calib 40 &
python calibration_runs.py free-zinc-calib 41 &
python calibration_runs.py free-zinc-calib 42 &
python calibration_runs.py free-zinc-calib 43 &
python calibration_runs.py free-zinc-calib 44 &
python calibration_runs.py free-zinc-calib 45 &
python calibration_runs.py free-zinc-calib 46 &
python calibration_runs.py free-zinc-calib 47
python calibration_runs.py free-zinc-calib 48 &
python calibration_runs.py free-zinc-calib 49 &
python calibration_runs.py free-zinc-calib 50 &
python calibration_runs.py free-zinc-calib 51 &
python calibration_runs.py free-zinc-calib 52 &
python calibration_runs.py free-zinc-calib 53 &
python calibration_runs.py free-zinc-calib 54 &
python calibration_runs.py free-zinc-calib 55 &
python calibration_runs.py free-zinc-calib 56 &
python calibration_runs.py free-zinc-calib 57 &
python calibration_runs.py free-zinc-calib 58 &
python calibration_runs.py free-zinc-calib 59 &
python calibration_runs.py free-zinc-calib 60 &
python calibration_runs.py free-zinc-calib 61 &
python calibration_runs.py free-zinc-calib 62 &
python calibration_runs.py free-zinc-calib 63 &
python calibration_runs.py free-zinc-calib 64 &
python calibration_runs.py free-zinc-calib 65 &
python calibration_runs.py free-zinc-calib 66 &
python calibration_runs.py free-zinc-calib 67 &
python calibration_runs.py free-zinc-calib 68 &
python calibration_runs.py free-zinc-calib 69 &
python calibration_runs.py free-zinc-calib 70 &
python calibration_runs.py free-zinc-calib 71
python calibration_runs.py free-zinc-calib 72 &
python calibration_runs.py free-zinc-calib 73 &
python calibration_runs.py free-zinc-calib 74 &
python calibration_runs.py free-zinc-calib 75 &
python calibration_runs.py free-zinc-calib 76 &
python calibration_runs.py free-zinc-calib 77 &
python calibration_runs.py free-zinc-calib 78 &
python calibration_runs.py free-zinc-calib 79 &
python calibration_runs.py free-zinc-calib 80 &
python calibration_runs.py free-zinc-calib 81 &
python calibration_runs.py free-zinc-calib 82 &
python calibration_runs.py free-zinc-calib 83 &
python calibration_runs.py free-zinc-calib 84 &
python calibration_runs.py free-zinc-calib 85 &
python calibration_runs.py free-zinc-calib 86 &
python calibration_runs.py free-zinc-calib 87 &
python calibration_runs.py free-zinc-calib 88 &
python calibration_runs.py free-zinc-calib 89 &
python calibration_runs.py free-zinc-calib 90 &
python calibration_runs.py free-zinc-calib 91 &
python calibration_runs.py free-zinc-calib 92 &
python calibration_runs.py free-zinc-calib 93 &
python calibration_runs.py free-zinc-calib 94 &
python calibration_runs.py free-zinc-calib 95
python calibration_runs.py free-zinc-calib 96 &
python calibration_runs.py free-zinc-calib 97 &
python calibration_runs.py free-zinc-calib 98 &
python calibration_runs.py free-zinc-calib 99 &
python calibration_runs.py free-zinc-calib 100 &
python calibration_runs.py free-zinc-calib 101 &
python calibration_runs.py free-zinc-calib 102 &
python calibration_runs.py free-zinc-calib 103 &
python calibration_runs.py free-zinc-calib 104 &
python calibration_runs.py free-zinc-calib 105 &
python calibration_runs.py free-zinc-calib 106 &
python calibration_runs.py free-zinc-calib 107 &
python calibration_runs.py free-zinc-calib 108 &
python calibration_runs.py free-zinc-calib 109 &
python calibration_runs.py free-zinc-calib 110 &
python calibration_runs.py free-zinc-calib 111 &
python calibration_runs.py free-zinc-calib 112 &
python calibration_runs.py free-zinc-calib 113 &
python calibration_runs.py free-zinc-calib 114 &
python calibration_runs.py free-zinc-calib 115 &
python calibration_runs.py free-zinc-calib 116 &
python calibration_runs.py free-zinc-calib 117 &
python calibration_runs.py free-zinc-calib 118 &
python calibration_runs.py free-zinc-calib 119
python calibration_runs.py free-zinc-calib 120 &
python calibration_runs.py free-zinc-calib 121 &
python calibration_runs.py free-zinc-calib 122 &
python calibration_runs.py free-zinc-calib 123 &
python calibration_runs.py free-zinc-calib 124 &
python calibration_runs.py free-zinc-calib 125 &
python calibration_runs.py free-zinc-calib 126 &
python calibration_runs.py free-zinc-calib 127 &
python calibration_runs.py free-zinc-calib 128 &
python calibration_runs.py free-zinc-calib 129 &
python calibration_runs.py free-zinc-calib 130 &
python calibration_runs.py free-zinc-calib 131 &
python calibration_runs.py free-zinc-calib 132 &
python calibration_runs.py free-zinc-calib 133 &
python calibration_runs.py free-zinc-calib 134 &
python calibration_runs.py free-zinc-calib 135 &
python calibration_runs.py free-zinc-calib 136 &
python calibration_runs.py free-zinc-calib 137 &
python calibration_runs.py free-zinc-calib 138 &
python calibration_runs.py free-zinc-calib 139 &
python calibration_runs.py free-zinc-calib 140 &
python calibration_runs.py free-zinc-calib 141 &
python calibration_runs.py free-zinc-calib 142 &
python calibration_runs.py free-zinc-calib 143
python calibration_runs.py free-zinc-calib 144 &
python calibration_runs.py free-zinc-calib 145 &
python calibration_runs.py free-zinc-calib 146 &
python calibration_runs.py free-zinc-calib 147 &
python calibration_runs.py free-zinc-calib 148 &
python calibration_runs.py free-zinc-calib 149 &
python calibration_runs.py free-zinc-calib 150 &
python calibration_runs.py free-zinc-calib 151 &
python calibration_runs.py free-zinc-calib 152 &
python calibration_runs.py free-zinc-calib 153 &
python calibration_runs.py free-zinc-calib 154 &
python calibration_runs.py free-zinc-calib 155 &
python calibration_runs.py free-zinc-calib 156 &
python calibration_runs.py free-zinc-calib 157 &
python calibration_runs.py free-zinc-calib 158 &
python calibration_runs.py free-zinc-calib 159 &
python calibration_runs.py free-zinc-calib 160 &
python calibration_runs.py free-zinc-calib 161 &
python calibration_runs.py free-zinc-calib 162 &
python calibration_runs.py free-zinc-calib 163 &
python calibration_runs.py free-zinc-calib 164 &
python calibration_runs.py free-zinc-calib 165 &
python calibration_runs.py free-zinc-calib 166 &
python calibration_runs.py free-zinc-calib 167
python calibration_runs.py free-zinc-calib 168 &
python calibration_runs.py free-zinc-calib 169 &
python calibration_runs.py free-zinc-calib 170 &
python calibration_runs.py free-zinc-calib 171 &
python calibration_runs.py free-zinc-calib 172 &
python calibration_runs.py free-zinc-calib 173 &
python calibration_runs.py free-zinc-calib 174 &
python calibration_runs.py free-zinc-calib 175 &
python calibration_runs.py free-zinc-calib 176 &
python calibration_runs.py free-zinc-calib 177 &
python calibration_runs.py free-zinc-calib 178 &
python calibration_runs.py free-zinc-calib 179 &
python calibration_runs.py free-zinc-calib 180 &
python calibration_runs.py free-zinc-calib 181 &
python calibration_runs.py free-zinc-calib 182 &
python calibration_runs.py free-zinc-calib 183 &
python calibration_runs.py free-zinc-calib 184 &
python calibration_runs.py free-zinc-calib 185 &
python calibration_runs.py free-zinc-calib 186 &
python calibration_runs.py free-zinc-calib 187 &
python calibration_runs.py free-zinc-calib 188 &
python calibration_runs.py free-zinc-calib 189 &
python calibration_runs.py free-zinc-calib 190 &
python calibration_runs.py free-zinc-calib 191
python calibration_runs.py free-zinc-calib 192 &
python calibration_runs.py free-zinc-calib 193 &
python calibration_runs.py free-zinc-calib 194 &
python calibration_runs.py free-zinc-calib 195 &
python calibration_runs.py free-zinc-calib 196 &
python calibration_runs.py free-zinc-calib 197 &
python calibration_runs.py free-zinc-calib 198 &
python calibration_runs.py free-zinc-calib 199 &
python calibration_runs.py free-zinc-calib 200 &
python calibration_runs.py free-zinc-calib 201 &
python calibration_runs.py free-zinc-calib 202 &
python calibration_runs.py free-zinc-calib 203 &
python calibration_runs.py free-zinc-calib 204 &
python calibration_runs.py free-zinc-calib 205 &
python calibration_runs.py free-zinc-calib 206 &
python calibration_runs.py free-zinc-calib 207 &
python calibration_runs.py free-zinc-calib 208 &
python calibration_runs.py free-zinc-calib 209 &
python calibration_runs.py free-zinc-calib 210 &
python calibration_runs.py free-zinc-calib 211 &
python calibration_runs.py free-zinc-calib 212 &
python calibration_runs.py free-zinc-calib 213 &
python calibration_runs.py free-zinc-calib 214 &
python calibration_runs.py free-zinc-calib 215
python calibration_runs.py free-zinc-calib 216 &
python calibration_runs.py free-zinc-calib 217 &
python calibration_runs.py free-zinc-calib 218 &
python calibration_runs.py free-zinc-calib 219 &
python calibration_runs.py free-zinc-calib 220 &
python calibration_runs.py free-zinc-calib 221 &
python calibration_runs.py free-zinc-calib 222 &
python calibration_runs.py free-zinc-calib 223 &
python calibration_runs.py free-zinc-calib 224 &
python calibration_runs.py free-zinc-calib 225 &
python calibration_runs.py free-zinc-calib 226 &
python calibration_runs.py free-zinc-calib 227 &
python calibration_runs.py free-zinc-calib 228 &
python calibration_runs.py free-zinc-calib 229 &
python calibration_runs.py free-zinc-calib 230 &
python calibration_runs.py free-zinc-calib 231 &
python calibration_runs.py free-zinc-calib 232 &
python calibration_runs.py free-zinc-calib 233 &
python calibration_runs.py free-zinc-calib 234 &
python calibration_runs.py free-zinc-calib 235 &
python calibration_runs.py free-zinc-calib 236 &
python calibration_runs.py free-zinc-calib 237 &
python calibration_runs.py free-zinc-calib 238 &
python calibration_runs.py free-zinc-calib 239
python calibration_runs.py free-zinc-calib 240 &
python calibration_runs.py free-zinc-calib 241 &
python calibration_runs.py free-zinc-calib 242 &
python calibration_runs.py free-zinc-calib 243 &
python calibration_runs.py free-zinc-calib 244 &
python calibration_runs.py free-zinc-calib 245 &
python calibration_runs.py free-zinc-calib 246 &
python calibration_runs.py free-zinc-calib 247 &
python calibration_runs.py free-zinc-calib 248 &
python calibration_runs.py free-zinc-calib 249 &
python calibration_runs.py free-zinc-calib 250 &
python calibration_runs.py free-zinc-calib 251 &
python calibration_runs.py free-zinc-calib 252 &
python calibration_runs.py free-zinc-calib 253 &
python calibration_runs.py free-zinc-calib 254 &
python calibration_runs.py free-zinc-calib 255 &
python calibration_runs.py free-zinc-calib 256 &
python calibration_runs.py free-zinc-calib 257 &
python calibration_runs.py free-zinc-calib 258 &
python calibration_runs.py free-zinc-calib 259 &
python calibration_runs.py free-zinc-calib 260 &
python calibration_runs.py free-zinc-calib 261 &
python calibration_runs.py free-zinc-calib 262 &
python calibration_runs.py free-zinc-calib 263
python calibration_runs.py free-zinc-calib 264 &
python calibration_runs.py free-zinc-calib 265 &
python calibration_runs.py free-zinc-calib 266 &
python calibration_runs.py free-zinc-calib 267 &
python calibration_runs.py free-zinc-calib 268 &
python calibration_runs.py free-zinc-calib 269 &
python calibration_runs.py free-zinc-calib 270 &
python calibration_runs.py free-zinc-calib 271 &
python calibration_runs.py free-zinc-calib 272 &
python calibration_runs.py free-zinc-calib 273 &
python calibration_runs.py free-zinc-calib 274 &
python calibration_runs.py free-zinc-calib 275 &
python calibration_runs.py free-zinc-calib 276 &
python calibration_runs.py free-zinc-calib 277 &
python calibration_runs.py free-zinc-calib 278 &
python calibration_runs.py free-zinc-calib 279 &
python calibration_runs.py free-zinc-calib 280 &
python calibration_runs.py free-zinc-calib 281 &
python calibration_runs.py free-zinc-calib 282 &
python calibration_runs.py free-zinc-calib 283 &
python calibration_runs.py free-zinc-calib 284 &
python calibration_runs.py free-zinc-calib 285 &
python calibration_runs.py free-zinc-calib 286 &
python calibration_runs.py free-zinc-calib 287
python calibration_runs.py free-zinc-calib 288 &
python calibration_runs.py free-zinc-calib 289 &
python calibration_runs.py free-zinc-calib 290 &
python calibration_runs.py free-zinc-calib 291 &
python calibration_runs.py free-zinc-calib 292 &
python calibration_runs.py free-zinc-calib 293 &
python calibration_runs.py free-zinc-calib 294 &
python calibration_runs.py free-zinc-calib 295 &
python calibration_runs.py free-zinc-calib 296 &
python calibration_runs.py free-zinc-calib 297 &
python calibration_runs.py free-zinc-calib 298 &
python calibration_runs.py free-zinc-calib 299 &
python calibration_runs.py free-zinc-calib 300 &
python calibration_runs.py free-zinc-calib 301 &
python calibration_runs.py free-zinc-calib 302 &
python calibration_runs.py free-zinc-calib 303 &
python calibration_runs.py free-zinc-calib 304 &
python calibration_runs.py free-zinc-calib 305 &
python calibration_runs.py free-zinc-calib 306 &
python calibration_runs.py free-zinc-calib 307 &
python calibration_runs.py free-zinc-calib 308 &
python calibration_runs.py free-zinc-calib 309 &
python calibration_runs.py free-zinc-calib 310 &
python calibration_runs.py free-zinc-calib 311
python calibration_runs.py free-zinc-calib 312 &
python calibration_runs.py free-zinc-calib 313 &
python calibration_runs.py free-zinc-calib 314 &
python calibration_runs.py free-zinc-calib 315 &
python calibration_runs.py free-zinc-calib 316 &
python calibration_runs.py free-zinc-calib 317 &
python calibration_runs.py free-zinc-calib 318 &
python calibration_runs.py free-zinc-calib 319 &
python calibration_runs.py free-zinc-calib 320 &
python calibration_runs.py free-zinc-calib 321 &
python calibration_runs.py free-zinc-calib 322 &
python calibration_runs.py free-zinc-calib 323 &
python calibration_runs.py free-zinc-calib 324 &
python calibration_runs.py free-zinc-calib 325 &
python calibration_runs.py free-zinc-calib 326 &
python calibration_runs.py free-zinc-calib 327 &
python calibration_runs.py free-zinc-calib 328 &
python calibration_runs.py free-zinc-calib 329 &
python calibration_runs.py free-zinc-calib 330 &
python calibration_runs.py free-zinc-calib 331 &
python calibration_runs.py free-zinc-calib 332 &
python calibration_runs.py free-zinc-calib 333 &
python calibration_runs.py free-zinc-calib 334 &
python calibration_runs.py free-zinc-calib 335
python calibration_runs.py free-zinc-calib 336 &
python calibration_runs.py free-zinc-calib 337 &
python calibration_runs.py free-zinc-calib 338 &
python calibration_runs.py free-zinc-calib 339 &
python calibration_runs.py free-zinc-calib 340 &
python calibration_runs.py free-zinc-calib 341 &
python calibration_runs.py free-zinc-calib 342 &
python calibration_runs.py free-zinc-calib 343 &
python calibration_runs.py free-zinc-calib 344 &
python calibration_runs.py free-zinc-calib 345 &
python calibration_runs.py free-zinc-calib 346 &
python calibration_runs.py free-zinc-calib 347 &
python calibration_runs.py free-zinc-calib 348 &
python calibration_runs.py free-zinc-calib 349 &
python calibration_runs.py free-zinc-calib 350 &
python calibration_runs.py free-zinc-calib 351 &
python calibration_runs.py free-zinc-calib 352 &
python calibration_runs.py free-zinc-calib 353 &
python calibration_runs.py free-zinc-calib 354 &
python calibration_runs.py free-zinc-calib 355 &
python calibration_runs.py free-zinc-calib 356 &
python calibration_runs.py free-zinc-calib 357 &
python calibration_runs.py free-zinc-calib 358 &
python calibration_runs.py free-zinc-calib 359
python calibration_runs.py free-zinc-calib 360 &
python calibration_runs.py free-zinc-calib 361 &
python calibration_runs.py free-zinc-calib 362 &
python calibration_runs.py free-zinc-calib 363 &
python calibration_runs.py free-zinc-calib 364 &
python calibration_runs.py free-zinc-calib 365 &
python calibration_runs.py free-zinc-calib 366 &
python calibration_runs.py free-zinc-calib 367 &
python calibration_runs.py free-zinc-calib 368 &
python calibration_runs.py free-zinc-calib 369 &
python calibration_runs.py free-zinc-calib 370 &
python calibration_runs.py free-zinc-calib 371 &
python calibration_runs.py free-zinc-calib 372 &
python calibration_runs.py free-zinc-calib 373 &
python calibration_runs.py free-zinc-calib 374 &
python calibration_runs.py free-zinc-calib 375 &
python calibration_runs.py free-zinc-calib 376 &
python calibration_runs.py free-zinc-calib 377 &
python calibration_runs.py free-zinc-calib 378 &
python calibration_runs.py free-zinc-calib 379 &
python calibration_runs.py free-zinc-calib 380 &
python calibration_runs.py free-zinc-calib 381 &
python calibration_runs.py free-zinc-calib 382 &
python calibration_runs.py free-zinc-calib 383
python calibration_runs.py free-zinc-calib 384 &
python calibration_runs.py free-zinc-calib 385 &
python calibration_runs.py free-zinc-calib 386 &
python calibration_runs.py free-zinc-calib 387 &
python calibration_runs.py free-zinc-calib 388 &
python calibration_runs.py free-zinc-calib 389 &
python calibration_runs.py free-zinc-calib 390 &
python calibration_runs.py free-zinc-calib 391 &
python calibration_runs.py free-zinc-calib 392 &
python calibration_runs.py free-zinc-calib 393 &
python calibration_runs.py free-zinc-calib 394 &
python calibration_runs.py free-zinc-calib 395 &
python calibration_runs.py free-zinc-calib 396 &
python calibration_runs.py free-zinc-calib 397 &
python calibration_runs.py free-zinc-calib 398 &
python calibration_runs.py free-zinc-calib 399 &
python calibration_runs.py free-zinc-calib 400 &
python calibration_runs.py free-zinc-calib 401 &
python calibration_runs.py free-zinc-calib 402 &
python calibration_runs.py free-zinc-calib 403 &
python calibration_runs.py free-zinc-calib 404 &
python calibration_runs.py free-zinc-calib 405 &
python calibration_runs.py free-zinc-calib 406 &
python calibration_runs.py free-zinc-calib 407
python calibration_runs.py free-zinc-calib 408 &
python calibration_runs.py free-zinc-calib 409 &
python calibration_runs.py free-zinc-calib 410 &
python calibration_runs.py free-zinc-calib 411 &
python calibration_runs.py free-zinc-calib 412 &
python calibration_runs.py free-zinc-calib 413 &
python calibration_runs.py free-zinc-calib 414 &
python calibration_runs.py free-zinc-calib 415 &
python calibration_runs.py free-zinc-calib 416 &
python calibration_runs.py free-zinc-calib 417 &
python calibration_runs.py free-zinc-calib 418 &
python calibration_runs.py free-zinc-calib 419 &
python calibration_runs.py free-zinc-calib 420 &
python calibration_runs.py free-zinc-calib 421 &
python calibration_runs.py free-zinc-calib 422 &
python calibration_runs.py free-zinc-calib 423 &
python calibration_runs.py free-zinc-calib 424 &
python calibration_runs.py free-zinc-calib 425 &
python calibration_runs.py free-zinc-calib 426 &
python calibration_runs.py free-zinc-calib 427 &
python calibration_runs.py free-zinc-calib 428 &
python calibration_runs.py free-zinc-calib 429 &
python calibration_runs.py free-zinc-calib 430 &
python calibration_runs.py free-zinc-calib 431
python calibration_runs.py free-zinc-calib 432 &
python calibration_runs.py free-zinc-calib 433 &
python calibration_runs.py free-zinc-calib 434 &
python calibration_runs.py free-zinc-calib 435 &
python calibration_runs.py free-zinc-calib 436 &
python calibration_runs.py free-zinc-calib 437 &
python calibration_runs.py free-zinc-calib 438 &
python calibration_runs.py free-zinc-calib 439 &
python calibration_runs.py free-zinc-calib 440 &
python calibration_runs.py free-zinc-calib 441 &
python calibration_runs.py free-zinc-calib 442 &
python calibration_runs.py free-zinc-calib 443 &
python calibration_runs.py free-zinc-calib 444 &
python calibration_runs.py free-zinc-calib 445 &
python calibration_runs.py free-zinc-calib 446 &
python calibration_runs.py free-zinc-calib 447 &
python calibration_runs.py free-zinc-calib 448 &
python calibration_runs.py free-zinc-calib 449